# Generated by Django 2.2 on 2020-08-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benchlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchConsultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bench_consultant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('visa', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('availability_date', models.CharField(blank=True, max_length=100, null=True)),
                ('bench_days', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'BenchConsultant',
                'verbose_name_plural': 'BenchConsultants',
            },
        ),
        migrations.CreateModel(
            name='ProspectConsultant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prospect_consultant_name', models.CharField(blank=True, max_length=100, null=True)),
                ('technology', models.CharField(blank=True, max_length=100, null=True)),
                ('trainer', models.CharField(blank=True, max_length=100, null=True)),
                ('training_status', models.CharField(blank=True, max_length=15, null=True)),
                ('availability_date', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'ProspectConsultant',
                'verbose_name_plural': 'ProspectConsultants',
            },
        ),
    ]
