# Generated by Django 2.2 on 2020-08-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benchlist', '0002_benchconsultant_prospectconsultant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benchconsultant',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
