# Generated by Django 2.2 on 2020-08-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benchlist', '0003_auto_20200804_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultant',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
