# Generated by Django 2.2 on 2020-08-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benchlist', '0005_auto_20200804_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant_name', models.CharField(max_length=100)),
                ('date_of_submission', models.DateField()),
                ('job_title', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('client', models.CharField(max_length=100)),
                ('client_city', models.CharField(max_length=100)),
                ('client_state', models.CharField(choices=[('fl', 'Florida'), ('hi', 'Hawaii'), ('ga', 'Georgia'), ('cl', 'California'), ('mt', 'Montana'), ('nj', 'New Jersey'), ('nm', 'New Mexico'), ('ny', 'New York')], max_length=100)),
                ('vendor_company', models.CharField(max_length=100)),
                ('vendor_recruiter_contact', models.CharField(max_length=100)),
                ('vendor_location', models.CharField(max_length=100)),
                ('submission_status', models.CharField(choices=[(1, 'Initial submission'), (2, 'Rate confirmed'), (3, 'Client submission'), (4, 'Interview'), (5, 'Project confirmed'), (6, 'On project'), (7, 'Rejected by vendor'), (8, 'Rejected in interview'), (9, 'Offer rejected')], default=1, max_length=100)),
                ('reason', models.CharField(blank=True, editable=False, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
            },
        ),
    ]
