# Generated by Django 2.2 on 2020-08-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benchlist', '0006_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date_of_submission',
            field=models.CharField(max_length=100),
        ),
    ]
