# Generated by Django 2.2 on 2020-08-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benchlist', '0007_auto_20200804_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date_of_submission',
            field=models.DateField(),
        ),
    ]
