# Generated by Django 2.2 on 2020-08-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benchlist', '0008_auto_20200804_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='rate_confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
