# Generated by Django 2.2 on 2020-08-05 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('benchlist', '0009_submission_rate_confirmation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='benchlist',
            old_name='bench_consultant_name',
            new_name='consultant_name',
        ),
        migrations.RenameField(
            model_name='prospectconsultant',
            old_name='prospect_consultant_name',
            new_name='consultant_name',
        ),
    ]
