# Generated by Django 2.2 on 2020-08-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('benchlist', '0012_auto_20200805_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='reason',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
